### ISSUE TITLE
`test_metrics_endpoint` fails to confirm metrics target

### ISSUE THREAD

**Issue by orfeas-k** [canonical/metacontroller-operator#138]
### Bug Description

During metrics endpoint assertion, integration tests fail with:
```
    assert target_data["state"] == "up", f"target for {app.name} is not in {target_data['state']}"
AssertionError: target for metacontroller-operator is not in unknown
```

This is probably because

### To Reproduce

Rerun CI

### Environment

Microk8s 1.29, juju 3.4

### Relevant Log Output

```shell
=================================== FAILURES ===================================
_____________________________ test_metrics_enpoint _____________________________
Traceback (most recent call last):
  File "/home/runner/work/metacontroller-operator/metacontroller-operator/.tox/integration/lib/python3.8/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/home/runner/work/metacontroller-operator/metacontroller-operator/.tox/integration/lib/python3.8/site-packages/_pytest/runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/home/runner/work/metacontroller-operator/metacontroller-operator/.tox/integration/lib/python3.8/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/home/runner/work/metacontroller-operator/metacontroller-operator/.tox/integration/lib/python3.8/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/runner/work/metacontroller-operator/metacontroller-operator/.tox/integration/lib/python3.8/site-packages/pluggy/_callers.py", line 152, in _multicall
    return outcome.get_result()
  File "/home/runner/work/metacontroller-operator/metacontroller-operator/.tox/integration/lib/python3.8/site-packages/pluggy/_result.py", line 114, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/home/runner/work/metacontroller-operator/metacontroller-operator/.tox/integration/lib/python3.8/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "/home/runner/work/metacontroller-operator/metacontroller-operator/.tox/integration/lib/python3.8/site-packages/_pytest/runner.py", line 177, in pytest_runtest_call
    raise e
  File "/home/runner/work/metacontroller-operator/metacontroller-operator/.tox/integration/lib/python3.8/site-packages/_pytest/runner.py", line 169, in pytest_runtest_call
    item.runtest()
  File "/home/runner/work/metacontroller-operator/metacontroller-operator/.tox/integration/lib/python3.8/site-packages/_pytest/python.py", line 1792, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/home/runner/work/metacontroller-operator/metacontroller-operator/.tox/integration/lib/python3.8/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/home/runner/work/metacontroller-operator/metacontroller-operator/.tox/integration/lib/python3.8/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/runner/work/metacontroller-operator/metacontroller-operator/.tox/integration/lib/python3.8/site-packages/pluggy/_callers.py", line 152, in _multicall
    return outcome.get_result()
  File "/home/runner/work/metacontroller-operator/metacontroller-operator/.tox/integration/lib/python3.8/site-packages/pluggy/_result.py", line 114, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/home/runner/work/metacontroller-operator/metacontroller-operator/.tox/integration/lib/python3.8/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "/home/runner/work/metacontroller-operator/metacontroller-operator/.tox/integration/lib/python3.8/site-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/home/runner/work/metacontroller-operator/metacontroller-operator/.tox/integration/lib/python3.8/site-packages/pytest_asyncio/plugin.py", line 532, in inner
    _loop.run_until_complete(task)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/runner/work/metacontroller-operator/metacontroller-operator/tests/integration/test_charm.py", line 67, in test_metrics_enpoint
    await assert_metrics_endpoint(app, metrics_port=9999, metrics_path="/metrics")
  File "/home/runner/work/metacontroller-operator/metacontroller-operator/.tox/integration/lib/python3.8/site-packages/charmed_kubeflow_chisme/testing/cos_integration.py", line 463, in assert_metrics_endpoint
    assert target_data["state"] == "up", f"target for {app.name} is not in {target_data['state']}"
AssertionError: target for metacontroller-operator is not in unknown
```

**Comment by orfeas-k** [comment]
After all, this was fixed by implementing a tenacity `retry` by default in chisme in https://github.com/canonical/charmed-kubeflow-chisme/pull/124 and then release a new version and bring it in the repo.
